//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYKalleMaintV01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFrame
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFrame()
        {
            this.CN_FrameScore = 0;
        }
    
        public int CN_FramePK { get; set; }
        public int CN_FrameSpilPK { get; set; }
        public int CN_FrameScore { get; set; }
        public int CN_FrameNr { get; set; }
    
        public virtual tblSpil tblSpil { get; set; }
    }
}
