//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYKalleMaintV01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSpil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSpil()
        {
            this.CN_SpilSesson = 0;
            this.CN_SpilPlacering = 0;
            this.CN_SpilGennemsnit = 0m;
            this.tblFrames = new HashSet<tblFrame>();
        }
    
        public int CN_SpilPK { get; set; }
        public int CN_SpilSpillerPK { get; set; }
        public System.DateTime CN_SpilDato { get; set; }
        public int CN_SpilSesson { get; set; }
        public Nullable<bool> CN_SpilKalleKamel { get; set; }
        public int CN_SpilPlacering { get; set; }
        public decimal CN_SpilGennemsnit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFrame> tblFrames { get; set; }
        public virtual tblSpiller tblSpiller { get; set; }
    }
}
