//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYKalleMaintV01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSpiller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSpiller()
        {
            this.tblSpils = new HashSet<tblSpil>();
        }
    
        public int CN_SpillerPK { get; set; }
        public string CN_SpillerForNavn { get; set; }
        public string CN_SpillerEfterNavn { get; set; }
        public string CN_SpillerInit { get; set; }
        public Nullable<System.DateTime> CN_SpillerOptDato { get; set; }
        public Nullable<System.DateTime> CN_SpillerUdMeldDato { get; set; }
        public Nullable<bool> CN_SpillerFormand { get; set; }
        public Nullable<bool> CN_SpillerNastFormand { get; set; }
        public Nullable<bool> CN_SpillerKasser { get; set; }
        public Nullable<bool> CN_SpillerRevisor { get; set; }
        public Nullable<bool> CN_SpillerSkemaAnsv { get; set; }
        public Nullable<bool> CN_SpillerWebAnsv { get; set; }
        public string CN_EMail { get; set; }
        public Nullable<bool> CN_AktivMedl { get; set; }
        public Nullable<bool> CN_PassivMedl { get; set; }
        public Nullable<bool> CN_ProveMedl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSpil> tblSpils { get; set; }
    }
}
